# meta
description: web系エンジニアの不定期更新な技術ブログです。RubyやReact、Goについて書いています。
keywords: 不定期更新,エンジニア,ブログ,blog,Rails,Ruby,Go

# Navigation
navigation:
- name: Home
  slug: home
  url: /
- name: Tech Log
  slug: tech-log
  url: /tags/tech-log/
- name: Books
  slug: books
  url: /tags/books/
- name: Others
  slug: others
  url: /tags/others/
- name: Archives
  slug: archives
  url: /archives
- name: About
  slug: about
  url: /about

# Friendly link
# links:
#   - name: 
#     url: 

# Social account
social:
- slug: twitter
  url: https://twitter.com/macoto_chan
- slug: github
  url: https://github.com/inomar
- slug: facebook
  url: # https://www.facebook.com/some
- slug: email
  url: info@inomar.me
- slug: rss
	url: /atom.xml

# Google_analytics
google_analytics: UA-93818826-2

# Local search
local_search:
  enable: true
  
# Favicon
#favicon: /image/favicon.ico
